---
title: "Do gender quotas increase the election of female MPs? An analysis of the correlation between intra-party gender quotas and electoral results in Australia"
author: "Sabrina Kreyzerman"
thanks: "Code and data from this analysis are available at: https://github.com/sabrinakreyzerman-k/Donaldson_Paper_Gender_in_Australian_Elections."
date: today
date-format: long
abstract: "Gender disparities among political candidates, within and across political parties, are not novel. Using data sourced from the Australian Electoral Commission (AEC), this analysis highlights the stark difference in female and male political candidates in the Australian House of Representatives. In a positive light, this paper will also support that there have been recent advancements in the number of female Australian political candidates serving as Members of Parliament, for instance, through gender quotas within parties."
execute: 
  echo: false
  message: false
  warning: false
format:
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
bibliography: references.bib
---

```{r}
#| label: setup

library(tidyverse) # A collection of data-related packages
library(janitor) # Helps clean datasets
library(AustralianPoliticians)
library(knitr)
library(kableExtra)
library(here)
```


```{r}
#| label: load-data

## Read in datasets ##
cleaned_politicians_data <- read_csv(here("Data/Clean/cleaned_politicians_data.csv"))
cleaned_party_data <- read_csv(here("Data/Clean/cleaned_party_data.csv"))
cleaned_mp_data <- read_csv(here("Data/Clean/cleaned_mp_data.csv"))
combined_politician_dataset <- read_csv(here("Data/Clean/combined_politician_dataset.csv"))
```




# Introduction

Introduction goes here.

# Methodology

## Data Collection

Data Collection goes here.

## Data Overview

```{r}
#| label: tbl-female-labor-mps
#| tbl-cap: "Number of female Labor Party MPs elected directly following new gender quotas"

combined_politician_dataset |> 
  filter(year_elected == '1993' | year_elected == "1996" | year_elected == "2013" | year_elected == "2016") |>
  filter(gender == "female") |>
  filter(partyName.x == 'Australian Labor Party') |>
  group_by(year_elected) |>
  count() |>
  ungroup() |>
  kable(
    col.names = c("Election Year", "Number of Female MPs"),
    booktabs = TRUE)
```

In @tbl-female-labor-mps, blah blah blah.

```{r}
#| label: tbl-female-liberal-mps
#| tbl-cap: "Number of female Liberal Party MPs elected directly following new Labor Party gender quotas"

combined_politician_dataset |> 
  filter(year_elected == '1993' | year_elected == "1996" | year_elected == "2013" | year_elected == "2016") |>
  filter(gender == "female") |>
  filter(partyName.x == 'Liberal Party of Australia') |>
  group_by(year_elected) |>
  count() |>
  ungroup() |>
  kable(
    col.names = c("Election Year", "Number of Female MPs"),
    booktabs = TRUE)
```

# Findings

Findings goes here.


 
# Discussion

Discussion goes here.

# Exclusions & Future Research

# Conclusion

Conclusion goes here.

# References